In [4]:
import numpy as np

In [5]:
mylist = [1,2,3]

In [6]:
type(mylist)

list

In [7]:
np.array(mylist)

array([1, 2, 3])

In [8]:
type(mylist)

list

In [9]:
myarray = np.array(mylist)

In [10]:
type(myarray)

numpy.ndarray

In [11]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [12]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [14]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [15]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [21]:
len(np.linspace(0,10,3))

3

In [22]:
np.random.rand(10)

array([0.38502591, 0.64844917, 0.17677278, 0.67732465, 0.34619016,
       0.37876199, 0.84926733, 0.65944783, 0.47600548, 0.91340962])

In [24]:
np.random.rand(2)

array([0.80039743, 0.09489753])

In [27]:
np.random.randn(4)

array([ 2.28043927, -0.04391576, -2.15941623, -0.14867979])

In [31]:
np.random.randint(0,10,5)

array([4, 8, 9, 9, 0])

In [32]:
np.random.randint(0,10,(2,2))

array([[0, 7],
       [1, 7]])

In [40]:
np.random.seed(42)
print(np.random.rand(), np.random.rand(), np.random.rand(), np.random.rand())

0.3745401188473625 0.9507143064099162 0.7319939418114051 0.5986584841970366


In [42]:
arr = np.random.randint(0,10,15)
arr

array([1, 4, 0, 9, 5, 8, 0, 9, 2, 6, 3, 8, 2, 4, 2])

In [43]:
arr.max()

np.int64(9)

In [44]:
arr.min()

np.int64(0)

In [45]:
arr.argmax()

np.int64(3)

In [46]:
arr.argmin()

np.int64(2)

In [48]:
arr.dtype

dtype('int64')

In [ ]:
arr = ['burger']

In [52]:
arr = np.array(arr)

In [53]:
arr.dtype

dtype('<U6')