In [2]:
import numpy as np

In [6]:
arr = np.arange(0,5)
arr[0 : 2] = 100
arr

array([100, 100,   2,   3,   4])

In [7]:
arr_copy = arr.copy()

In [8]:
arr_copy

array([100, 100,   2,   3,   4])

In [9]:
arr_copy[:] = 100
arr_copy

array([100, 100, 100, 100, 100])

Selection

In [15]:
arr_2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr_2d[0,2])
arr_2d.shape

3


(3, 3)

In [17]:
arr_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
print(arr_2d[:2,1:]) 

[[2 3]
 [5 6]]


In [17]:
dice_rolls = np.array([3, 1, 5, 2, 5, 1, 1, 5, 1, 4, 2, 1, 4, 5, 3, 4, 5, 2, 4, 2, 6, 6, 3, 6, 2, 3, 5, 6, 5])

In [ ]:
total_rolls_over_two = len([x for x in dice_rolls if x > 2])

In [23]:
total_rolls_over_two 

19