In [1]:
import numpy as np

In [18]:
arr = np.arange(0,10)

In [19]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
print(arr+5)

[ 5  6  7  8  9 10 11 12 13 14]


In [22]:
print(arr**arr)

[        1         1         4        27       256      3125     46656
    823543  16777216 387420489]


Instead of showing fully errors, it's just showing small error/ a warning but still gives output for other elements in array

In [23]:
print(arr/arr)

[nan  1.  1.  1.  1.  1.  1.  1.  1.  1.]


/tmp/ipykernel_210441/3742253236.py:1: RuntimeWarning: invalid value encountered in divide
  print(arr/arr)


Sum of elements in an array

In [24]:
print(arr.sum())

45


To get mean of an array

In [25]:
print(arr.mean())

4.5


To get variance of elements in an array

In [26]:
print(arr.var())

8.25


To get standard deviation of elements in an array

In [27]:
print(arr.std())

2.8722813232690143


All we did was for 1 dimensional array, now let's do for multiple and check

In [32]:
arr2d = np.arange(0,25).reshape(5,5)
print(arr2d)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


Let's check sum

In [37]:
print(arr2d.sum())

300


Variance

In [34]:
print(arr2d.var())

52.0


Standard deviation

In [35]:
print(arr2d.std())

7.211102550927978


Now if we want to get sum of only columns/ rows:

In [42]:
print(arr.sum(0)) # columns = 0

[50 55 60 65 70]


In [43]:
print(arr.sum(1)) # rows = 1

[ 10  35  60  85 110]
